import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-mono px-6">
        <h1 className="text-3xl font-bold underline p-2">Prog Touch</h1>
      </main>
    </>
  )
}
